<?php
namespace Fobia\Api\Method;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-03 at 23:00:52.
 */
class CallableMethodTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CallableMethod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // $this->object = new CallableMethod;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }



    public function testInvoke()
    {
        // $this->markTestIncomplete( 'This test has not been implemented yet.' );
        $this->assertInstanceOf("\\Fobia\\Base\Application", \AppTest::instance());

        //$app = \AppTest::instance();
        // echo $app->config('mode');
    }
}
