<?php
namespace Fobia\Api\Method;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-03 at 23:00:46.
 */
class FileMethodTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileMethod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new FileMethod;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testInvoke()
    {
        $this->assertTrue(true);
    }
}
