<?php

namespace Fobia\Api\Method;

use Fobia\Api\Method\Method;

class MyMethod extends Method
{
    protected function execute()
    {

    }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-03 at 22:58:33.
 */
class MethodTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Method
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // $this->object = new Method;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Fobia\Api\Method\Method::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Api\Method\Method::invoke
     * @todo   Implement testInvoke().
     */
    public function testInvoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Api\Method\Method::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Api\Method\Method::getFormatResponse
     * @todo   Implement testGetFormatResponse().
     */
    public function testGetFormatResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Api\Method\Method::errorInfo
     * @todo   Implement testErrorInfo().
     */
    public function testErrorInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Api\Method\Method::ignoreValidationErrors
     * @todo   Implement testIgnoreValidationErrors().
     */
    public function testIgnoreValidationErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Api\Method\Method::getDefinition
     * @todo   Implement testGetDefinition().
     */
    public function testGetDefinition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Api\Method\Method::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    
}