<?php

namespace Fobia\DataBase\Query;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-24 at 06:56:20.
 */
class QueryInsertTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Fobia\DataBase\Handler\MySQL
     */
    protected $db;
    protected $q;

    protected function setUp()
    {
        if ( ! $this->db) {
            $this->db = \Fobia\DataBase\DbFactory::create('mysql://root@localhost/mysql');
        }
        $this->q = $this->db->createInsertQuery();
    }

    public function testInsertQuery()
    {
        $q = $this->q;
        $this->assertInstanceOf('\Fobia\DataBase\Query\QueryInsert', $q);
    }

    /**
     * @covers Fobia\DataBase\Query\QueryInsert::insertIntoIgnore
     * @todo   Implement testInsertIntoIgnore().
     */
    public function testInsertIntoIgnore()
    {
        $q = $this->q;
        $q->insertIntoIgnore('user');
        $q->set("Host", "'localhost'");

        $stmt = $q->prepare();
        $this->assertStringStartsWith("INSERT IGNORE INTO user", $stmt->queryString);
    }

    /**
     * @covers Fobia\DataBase\Query\QueryInsert::getQuery
     * @todo   Implement testGetQuery().
     */
    public function testGetQuery()
    {
        $q = $this->db->createInsertQuery();

        $str = "INSERT INTO user ( Host, User, Password ) VALUES ( 'localhost', 'test', '' )";
        $q
                ->set('Host', $this->db->quote('localhost'))
                ->set('User', $this->db->quote('test'))
                ->set('Password', $this->db->quote(''));
        $qi = clone $q;

        $q->insertInto('user');
        $qi->insertIntoIgnore('user');

        $this->assertEquals($str, $q->getQuery());
        $this->assertRegExp('/^INSERT IGNORE /', $qi->getQuery());
    }
}