<?php

namespace Fobia\DataBase\Query;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-24 at 07:00:37.
 */
class QuerySelectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Fobia\DataBase\Handler\MySQL
     */
    protected $db;

    /**
     * @var \Fobia\DataBase\Query\QuerySelect
     */
    protected $q;

    protected function setUp()
    {
        if ( ! $this->db) {
            $this->db = \Fobia\DataBase\DbFactory::create('mysql://root@localhost/mysql');
        }
        $this->q = $this->db->createSelectQuery();
    }
    /**
     * @covers Fobia\DataBase\Query\QuerySelect::fetchItemsCount
     * @todo   Implement testFetchItemsCount().
     */
//    public function testFetchItemsCount()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\DataBase\Query\QuerySelect::findAll
     * @todo   Implement testFindAll().
     */
//    public function testFindAll()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\DataBase\Query\QuerySelect::offset
     * @todo   Implement testOffset().
     */
//    public function testOffset()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\DataBase\Query\QuerySelect::reset
     * @todo   Implement testReset().
     */
    public function testReset()
    {
        $q     = $this->q;
        $q->select('*')->from('user')
                ->limit(50, 10)
                ->orderBy('host')
                ->where("user = 'root'")
                ->groupBy('select')
                ->having($q->expr->eq('id', 1));
        // echo $q->getQuery();
        $query = "SELECT * FROM user WHERE user = 'root' GROUP BY select HAVING id = 1 ORDER BY host LIMIT 50 OFFSET 10";
        $this->assertEquals($query, $q->getQuery());

        $qFull = clone $q;

        return $q;
    }

    /**
     * @depends testReset
     */
    public function testResetFull($qFull)
    {
        $q = clone $qFull;

        $q->reset();
        $q->select('*')->from('user');
        $this->assertEquals("SELECT * FROM user", $q->getQuery());
        
        // selct
        $q = clone $qFull;
        $q->reset('select');
        $q->select('Host');
        $this->assertRegExp('/^SELECT * FROM user/', $q->getQuery());
        
        // from
        $q = clone $qFull;
        $q->reset('from');
        $q->from("Host");
        $this->assertRegExp('/^SELECT * FROM Host/', $q->getQuery());

        $q = clone $qFull;
        $q->reset('limit');
        $this->assertRegExp('/^SELECT * FROM Host/', $q->getQuery());
    }

    /**
     * @expectedException \ezcDbMissingParameterException
     */
    public function testResetException()
    {
        $this->q->reset('no name');
    }
}