<?php
namespace Fobia\Debug\Processor;


class MyStderrProcessor extends StderrProcessor
{
    protected $handle = null;

    public function __construct()
    {
        // $this->handle = fopen('php://temp', 'r+');
       //  $this->handle = fopen('php://stdout', 'a+');
        $this->handle = fopen('php://output', 'w');

        //feof($this->stream);
        //fseek($this->handle, 0, $SEEK_SET);
        //$body = stream_get_contents($this->handle, -1, 0);
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-08 at 13:10:27.
 */
class StderrProcessorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MyStderrProcessor
     */
    protected $proc;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->proc = new MyStderrProcessor();
    }


    /**
     * @covers Fobia\Debug\Processor\StderrProcessor::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke()
    {
        $this->expectOutputString('[info]  message context' . PHP_EOL);

        $record = array(
            'level' => 'info',
            'message' => 'message',
            'context' => 'context'
        );

        $proc = $this->proc;
        $record = $proc($record);
        return $record;
        // var_dump($this->proc);
    }

    /**
     * @covers Fobia\Debug\Processor\StderrProcessor::write
     * @todo   Implement testWrite().
     * @depends test__invoke
     */
    public function testWrite($record)
    {
        $this->expectOutputString('[info]  message context' . PHP_EOL);

        $this->proc->write($record);
    }

}
