<?php

namespace Fobia\DataBase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-24 at 06:31:43.
 */
class DbFactoryTest extends \PHPUnit_Framework_TestCase
{

    public function testCreate()
    {
        $db = \Fobia\DataBase\DbFactory::create('mysql://root@localhost/mysql');
        $this->assertInstanceOf('PDO', $db);
    }

    public function testCreate1()
    {
        $params = array(
            'host'   => 'localhost',
            'dbname' => 'mysql',
            'user'   => 'root',
            'pass'   => ''
        );
        $db     = \Fobia\DataBase\DbFactory::create($params);
        $this->assertInstanceOf('PDO', $db);
    }

//    public function functionName()
//    {
//        $db = \Fobia\DataBase\DbFactory::create('mysql://root@localhost/mysql');
//
//        /* @var $db \Fobia\DataBase\Handler\DbConnectionMysql */
//
//        $q    = $db->createSelectQuery();
//        $q->select('*')->from('user')->limit(10);
//        $stmt = $q->prepare();
//        $stmt->execute();
//        var_dump($stmt->fetchAll());
//    }
}