<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-04 at 07:21:04.
 */
class AppTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers App::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        $this->assertInstanceOf("\\Fobia\\Base\Application", \App::create());
    }

    protected static $_instance = null;

    public static function instance()
    {
        if (self::$_instance == null) {
            self::$_instance = self::create();
        }
        return self::$_instance;
    }

    public static function create()
    {
        $config = array(
            'file' => CONFIG_DIR . '/config.php',
            'mode' => "testing"
        );
        $app = new \Fobia\Base\Application($config);
        // $app->con
        return $app;
    }
}