<?php

use \Fobia\Base\Application;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-04 at 07:21:04.
 */
class AppTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers App::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        $this->assertInstanceOf("\\Fobia\\Base\Application", \App::create());
    }

    /**
     *
     * @return \Fobia\Base\Application
     */
    public static function instance()
    {
        $app = Application::getInstance();
        if (!$app) {
            $app = self::create();
        }
        return $app;
    }

    /**
     *
     * @return \Fobia\Base\Application
     */
    public static function create()
    {
        $config = array(
            'file' => CONFIG_DIR . '/config.php',
            'mode' => Application::MODE_TESTING
        );
        $app = new Application($config);
        // $app->setName('default');
        return $app;
    }
}