<?php
namespace Fobia\DataBase;

use Fobia\DataBase\DbFactory;
//use Fobia\DataBase\DbStatement;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-24 at 02:06:17.
 */
class DbFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DbFactory
     */
    protected $db;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->db = DbFactory::create('mysql://root@localhost/test');
    }

    /**
     * @covers Fobia\DataBase\DbFactory::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        $db = DbFactory::create('mysql://root@localhost/test');
        $this->assertInstanceOf('\\PDO', $db);
    }
}
