<?php
namespace Fobia\Debug;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-08 at 13:10:22.
 * @covers Fobia\Debug\ArrayLogger
 */
class ArrayLoggerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayLogger
     */
    protected $logger;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->logger = new ArrayLogger();
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::log
     */
    public function testLog()
    {
        $this->expectOutputRegex("/message/");
        $row = $this->logger->log(\Psr\Log\LogLevel::INFO, "message");
        print_r($row);
        return $this->logger;
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::getRows
     * @todo   Implement testGetRows().
     */
    public function testGetRows()
    {
        $this->logger->log(\Psr\Log\LogLevel::INFO, "message get rows");

        $rows = $this->logger->getRows();
        $r = array_pop($rows);

        $this->assertEquals("message get rows", $r['message']);
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::getLevelCode
     * @todo   Implement testGetLevelCode().
     */
    public function testGetLevelCode()
    {
        $this->assertEquals(200, ArrayLogger::getLevelCode(\Psr\Log\LogLevel::INFO));
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::getLevelName
     * @todo   Implement testGetLevelName().
     */
    public function testGetLevelName()
    {
        $this->assertEquals(\Psr\Log\LogLevel::INFO, ArrayLogger::getLevelName(200));
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        $str = $this->logger->render();
        $this->assertRegExp("/ac-logger-switch/", $str);

    }
}
