<?php
namespace Fobia\Debug;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-08 at 13:10:22.
 */
class ArrayLoggerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayLogger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::log
     * @todo   Implement testLog().
     */
    public function testLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::getRows
     * @todo   Implement testGetRows().
     */
    public function testGetRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::getLevelCode
     * @todo   Implement testGetLevelCode().
     */
    public function testGetLevelCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::getLevelName
     * @todo   Implement testGetLevelName().
     */
    public function testGetLevelName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Debug\ArrayLogger::registry
     * @todo   Implement testRegistry().
     */
    public function testRegistry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
