<?php

namespace Fobia\DataBase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-01 at 00:52:22.
 */
class DbStatementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Fobia\DataBase\Handler\MySQL
     */
    protected $db;

    protected function setUp()
    {
        if ( ! $this->db) {
            $this->db = \Fobia\DataBase\DbFactory::create('mysql://root@localhost/mysql');
        }
    }

    /**
     * @covers Fobia\DataBase\DbStatement::execute
     * @todo   Implement testExecute().
     */
    public function testExecute()
    {
        $stmt = $this->db->query("SELECT VERSION()");
        $stmt->execute();
    }

    /**
     * @covers Fobia\DataBase\DbStatement::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        $stmt = $this->db->query("SELECT VERSION()");
        unset($stmt);
    }
}