<?php

namespace Fobia\DataBase\Query;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-24 at 07:00:37.
 */
class QuerySelectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Fobia\DataBase\Handler\MySQL
     */
    protected $db;

    protected function setUp()
    {
        if ( ! $this->db) {
            $this->db = \Fobia\DataBase\DbFactory::create('mysql://root@localhost/mysql');
        }
    }

    /**
     * @covers Fobia\DataBase\Query\QuerySelect::fetchItemsCount
     * @todo   Implement testFetchItemsCount().
     */
//    public function testFetchItemsCount()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\DataBase\Query\QuerySelect::findAll
     * @todo   Implement testFindAll().
     */
//    public function testFindAll()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\DataBase\Query\QuerySelect::offset
     * @todo   Implement testOffset().
     */
//    public function testOffset()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\DataBase\Query\QuerySelect::reset
     * @todo   Implement testReset().
     */
    public function testReset()
    {
        $q = $this->db->createSelectQuery();
        $q->select('*')->from('user');
        $this->assertEquals('SELECT * FROM user', $q->getQuery());
        
        $q->reset();
        $q->select('Host')->from('user');

        $this->assertEquals('SELECT Host FROM user', $q->getQuery());
    }
}