<?php
namespace Fobia\Base;

use Fobia\Base\Application;
use App;


class MyAppController extends \Fobia\Base\Controller
{
    public function myAction()
    {
        echo __FUNCTION__;
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-03 at 22:43:54.
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Application
     */
    protected $app;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->app = \AppTest::create();
    }

    /**
     * @covers Fobia\Base\Application::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        $this->assertInstanceOf('\\Fobia\\Base\\Application', Application::getInstance());
    }

    /**
     * @covers Fobia\Base\Application::getInstance
     * @expectedException \RuntimeException
     */
    public function testGetInstanceException()
    {
        Application::getInstance('none');
    }

    /**
     * @covers Fobia\Base\Application::setInstance
     * @todo   Implement testSetInstance().
     */
    public function testSetInstance()
    {
        $app0 = Application::getInstance();
        $app1 = new Application();
        $app1['foo'] = 'bar';

        $this->assertEquals($app0, $this->app);
        $this->assertEquals($app0, Application::getInstance());
        $this->assertNotEquals($app1, $this->app);
        $this->assertNotEquals($app1, Application::getInstance());

        Application::setInstance($app1, 1);
        $this->assertEquals($app0, Application::getInstance(0));
        $this->assertNotEquals($app0, Application::getInstance(1));
        $this->assertEquals($app1, Application::getInstance(1));

        $app = Application::getInstance(1);
        $this->assertEquals('bar', $app['foo']);
    }

    public function testCreateController()
    {
        $this->expectOutputString('myAction');

        $this->app['settings']['controller.action_prefix'] = '';
        $this->app['settings']['controller.action_suffix'] = '';
        $this->app['settings']['controller.prefix'] = '';
        $this->app['settings']['controller.suffix'] = '';

        $func = $this->app->createController('\Fobia\Base\MyAppController:myAction');
        $func();
    }
}
