<?php
namespace Fobia\Base;

use Fobia\Base\Application;
use App;


class MyAppController extends \Fobia\Base\Controller
{
    public function myAction()
    {
        echo __FUNCTION__;
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-03 at 22:43:54.
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Application
     */
    protected $app;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->app = \AppTest::instance();
    }

    /**
     * @covers Fobia\Base\Application::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        $this->assertInstanceOf('\\Fobia\\Base\\Application', Application::getInstance());
    }

    /**
     * @covers Fobia\Base\Application::getInstance
     */
    public function testGetInstanceNone()
    {
        $this->assertNull(Application::getInstance('none'));
    }

    /**
     * @covers Fobia\Base\Application::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        $app = Application::getInstance();

        $app_2 = new Application();
        $app_2['foo'] = 'bar';

        $this->assertEquals($app, $this->app);
        $this->assertEquals($app, Application::getInstance());
        $this->assertNotEquals($app_2, $this->app);
        $this->assertNotEquals($app_2, Application::getInstance());

        $app_2->setName('app_1');
        $this->assertEquals($app, Application::getInstance());
        $this->assertNotEquals($app, Application::getInstance('app_1'));
        $this->assertEquals($app_2, Application::getInstance('app_1'));

        $app = Application::getInstance('app_1');
        $this->assertEquals('bar', $app['foo']);
    }
/**/
    public function testCreateController()
    {
        $this->expectOutputString('myAction');

        $this->app['settings']['controller.action_prefix'] = '';
        $this->app['settings']['controller.action_suffix'] = '';
        $this->app['settings']['controller.prefix'] = '';
        $this->app['settings']['controller.suffix'] = '';

        $func = $this->app->createController('\Fobia\Base\MyAppController:myAction');
        $func();
    }
}
