<?php
namespace Fobia\Base;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-07 at 12:00:56.
 */
class ObjectCollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ObjectCollection
     */
    protected $object;

    public function newItem($key1)
    {
        $arr = array(
            'key1' => $key1
        );
        $args = func_get_args();
        array_shift($args);
        foreach ($args as $k => $v) {
            $k = $k +2;
            $k = 'key'. $k;
            $arr[$k] = $v;
        }
        return $arr;
    }


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $arrs = array(
            $this->newItem(1),
            $this->newItem(2),
            $this->newItem(3),
        );
        $this->object = new ObjectCollection($arrs);
    }

    /**
     * @covers Fobia\Base\ObjectCollection::eq
     * @todo   Implement testEq().
     */
    public function testEq()
    {
        $obj = $this->object->eq();
        $this->assertEquals(1, $obj->key1);
    }

    /**
     * @covers Fobia\Base\ObjectCollection::find
     * @todo   Implement testFind().
     */
//    public function testFind()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::set
     * @todo   Implement testSet().
     */
//    public function testSet()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::get
     * @todo   Implement testGet().
     */
//    public function testGet()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::addAt
     * @todo   Implement testAddAt().
     */
//    public function testAddAt()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::merge
     * @todo   Implement testMerge().
     */
//    public function testMerge()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::removeAt
     * @todo   Implement testRemoveAt().
     */
//    public function testRemoveAt()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::remove
     * @todo   Implement testRemove().
     */
//    public function testRemove()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::each
     * @todo   Implement testEach().
     */
//    public function testEach()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::sort
     * @todo   Implement testSort().
     */
//    public function testSort()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::count
     * @todo   Implement testCount().
     */
//    public function testCount()
//    {
//        $this->assertEquals(3, $this->object->count());
//    }

    /**
     * @covers Fobia\Base\ObjectCollection::getIterator
     * @todo   Implement testGetIterator().
     */
    public function testGetIterator()
    {
        $arr = $this->object->getIterator();
        $this->assertInternalType('object', $arr[0]);
        $this->assertInstanceOf('\\ArrayIterator', $arr);

        $i = 0;
        foreach ($this->object as $key => $value) {
            $this->assertEquals($i, $key);
            $i++;
            $this->assertEquals($i, $value->key1 );
        }
    }

    /**
     * @covers Fobia\Base\ObjectCollection::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        $arr = $this->object->toArray();
        $this->assertInternalType('array', $arr);
        $this->assertInternalType('object', $arr[0]);
    }
}
