<?php
namespace Fobia\Api;

use Fobia\Api\Method as Method;

class MyApiHandler extends ApiHandler
{
    public function getMap()
    {
        return $this->apiMap;
    }
}

class MyMethod_ApiHandler extends Method
{
    protected function execute()
    {
        $this->response = 1;
    }
}


/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-07 at 14:44:53.
 */
class ApiHandlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MyApiHandler
     */
    protected $api;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $app = \AppTest::instance();
        $this->api = new MyApiHandler();
    }

    /**
     * @covers Fobia\Api\ApiHandler::addMap
     * @todo   Implement testAddMap().
     */
    public function testAddMapArray()
    {
        $method = array(
            'test.oneFirst' => array('file', __DIR__ . '/apiMethods/test.one.php', array('log' => true) )
        );
        $this->api->addMap($method);
        $apiMap = $this->api->getMap();

        $this->assertArrayHasKey('test.oneFirst', $apiMap);
        $this->assertEquals($method['test.oneFirst'], $apiMap['test.oneFirst']);

        return $this->api;
    }

    /**
     * @covers Fobia\Api\ApiHandler::addMap
     * @todo   Implement testAddMap().
     */
    public function testAddMapFile()
    {
        $file = __DIR__ . '/apimap.php';
        $this->api->addMap($file);

        $apiMap = $this->api->getMap();
        $this->assertArrayHasKey('test.one', $apiMap);
    }

    /**
     * @covers Fobia\Api\ApiHandler::request
     * @todo   Implement testRequest().
     * @depends testAddMapArray
     */
    public function testRequest($api)
    {
        $file = include __DIR__ . '/apimap.php';
        $api->addMap($file);

        $result = $api->request('test.one');
        $this->assertArrayHasKey("response", $result);
        $this->assertArrayHasKey("response", $api->request('test.oneFirst'));
    }


    /**
     * @covers Fobia\Api\ApiHandler::request
     */
    public function testRequest2()
    {
        $map = array(
            'test.class' => array('class', '\\Fobia\\Api\\MyMethod_ApiHandler')
        );
        $this->api->addMap($map);
        $this->assertArrayHasKey("response", $this->api->request('test.class'));
    }

    /**
     * @covers Fobia\Api\ApiHandler::request
     */
    public function testRequest3()
    {
        $callable = function() {
            return 1;
        };
        $map = array(
            'test.callable' => array('callable', $callable)
        );
        $this->api->addMap($map);
        $this->assertArrayHasKey("response", $this->api->request('test.callable'));
    }

    /**
     * @covers Fobia\Api\ApiHandler::getClass
     * @todo   Implement testGetClass().
     */
    public function testGetClass()
    {
        $className = $this->api->getClass('package.getName', false);
        $this->assertEquals("Api_Package_GetName", $className);
    }

}
