<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-03 at 22:55:23.
 */
class Api_Stdata_GetCountriesTest extends PHPUnit_Framework_TestCase
{

    protected $app;

    /**
     * @var Api_Stdata_GetCountries
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (!$this->app) {
            $this->app = \App::create();
        }
        // $this->object = new Api_Stdata_GetCountries;
    }

    public function testInvoke()
    {
        $object = new Api_Stdata_GetCountries();
        $object->ignoreValidationErrors();
        $object->invoke();

        $this->assertArrayHasKey('response', $object->getFormatResponse());
    }
}