<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'api_auth_login' => '/auth/auth.login.php',
                'api_auth_logout' => '/auth/auth.logout.php',
                'api_stdata_getcities' => '/stdata/stdata.getCities.php',
                'api_stdata_getcitiesbyid' => '/stdata/stdata.getCitiesById.php',
                'api_stdata_getcountries' => '/stdata/stdata.getCountries.php',
                'api_stdata_getcountriesbyid' => '/stdata/stdata.getCountriesById.php',
                'api_stdata_getregions' => '/stdata/stdata.getRegions.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
