<?php
namespace Fobia\Auth;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-07 at 12:28:46.
 */
class BaseUserIdentityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BaseUserIdentity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseUserIdentity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::getRoles
     * @todo   Implement testGetRoles().
     */
    public function testGetRoles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::getUsername
     * @todo   Implement testGetUsername().
     */
    public function testGetUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::getPassword
     * @todo   Implement testGetPassword().
     */
    public function testGetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::setUserData
     * @todo   Implement testSetUserData().
     */
    public function testSetUserData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::isRole
     * @todo   Implement testIsRole().
     */
    public function testIsRole()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::isAccess
     * @todo   Implement testIsAccess().
     */
    public function testIsAccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::getAccess
     * @todo   Implement testGetAccess().
     */
    public function testGetAccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::readData
     * @todo   Implement testReadData().
     */
    public function testReadData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Auth\BaseUserIdentity::setOnline
     * @todo   Implement testSetOnline().
     */
    public function testSetOnline()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
